- name: install EPEL
  yum:
    name: epel-release
    state: present

- name: install dci-agent
  yum:
    name: https://packages.distributed-ci.io/dci-release.el7.noarch.rpm
    state: present

- name: install dci-ansible
  yum:
    name: dci-ansible
    state: present

- name: temp fix for bug with requests requirment
  lineinfile:
    path: /usr/lib/python2.7/site-packages/dciclient-0.3.3-py2.7.egg-info/requires.txt
    regexp: '^requests'
    line: 'requests'

- name: set up connection information
  template:
    src: templates/env.sh
    dest: /etc/profile.d/dci_credentials.sh
    owner: root
    group: root
    mode: 744
